conn &&INOUT_USER/&&INOUT_PASS@&&TNS
--  ///////
--  ///////     Script Gerado a partir do Sistema Gerenciador de Interfaces IN-OUT
--  ///////     TABELA: BG_CONDICAO_PAGAMENTO
--  ///////

delete from DEPEND_HEADER_ITEM_TMP;

delete from COLUNAS_TAB_INTERFACE where TABLE_NAME = 'BG_CONDICAO_PAGAMENTO';

begin

  update	TAB_INTERFACE             
  set		DESCRICAO = '',
		CTL_NAME = 'BG_CONDICAO_PAGAMENTO', 
		PREFIX_FILE = 'COPGH', 
		GERAR_CTL = 'S', 
		PRIORIDADE = 0, 
		ODBC_SOURCE_NAME = '', 
		ODBC_USER = '', 
		ODBC_PASSWORD = '', 
		ODBC_TABLE_NAME = '', 
		ODBC_WHERE = '', 
		ODBC_SELECT_ESPECIFICO = '', 
		TIPO_INTERFACE = 'LOADER',
		ORACLE_INITIAL_EXTENT = '', 
		ORACLE_NEXT_EXTENT = '', 
		ORACLE_INDEX_TABLESPACE = '',
		ELIMINAR_REG_EXECUCAO = 'N',
		ID_SISTEMA = 'BG',
		PROCEDURE_NAME = 'PKG_SFW_COND_PAGAMENTO.PRC_COND_PAGTO',
		SEPARADOR = '',
		CTL_FIXO = null,
		TRIGGER1 = null,
		TRIGGER2 = null,
		COMANDO_EXTRA_LOADER = ''
  where TABLE_NAME = 'BG_CONDICAO_PAGAMENTO';

  if SQL%notfound then
		insert into TAB_INTERFACE 
		(TABLE_NAME,
		DESCRICAO, 
		CTL_NAME, 
		PREFIX_FILE, 
		GERAR_CTL, 
		PRIORIDADE, 
		ODBC_SOURCE_NAME, 
		ODBC_USER, 
		ODBC_PASSWORD, 
		ODBC_TABLE_NAME, 
		ODBC_WHERE, 
		ODBC_SELECT_ESPECIFICO, 
		TIPO_INTERFACE, 
		ORACLE_INITIAL_EXTENT, 
		ORACLE_NEXT_EXTENT, 
		ORACLE_INDEX_TABLESPACE, 
		ELIMINAR_REG_EXECUCAO, 
		COMANDO_EXTRA_LOADER, 
		ID_SISTEMA, 
		PROCEDURE_NAME, 
		SEPARADOR)
		values
		('BG_CONDICAO_PAGAMENTO',
		'',
		'BG_CONDICAO_PAGAMENTO', 
		'COPGH', 
		'S', 
		0, 
		'', 
		'', 
		'', 
		'', 
		'', 
		'', 
		'LOADER', 
		'', 
		'', 
		'',
		'N',
		'',
		'BG',
		'PKG_SFW_COND_PAGAMENTO.PRC_COND_PAGTO',
		'');
  end if;
end;
/


insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'COD_COND_PAGTO', 'CHAR', '', '', '20', 
'1','Código da Condição de Pagamento','PI_COD_COND_PAGTO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'COD_SISTEMA', 'CHAR', '', '', '10', 
'2','Código do Sistema','PI_COD_SISTEMA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'DESC_COND_PAGTO', 'CHAR', '', '', '150', 
'3','Descrição da Condição de Pagamento','PI_DESC_COND_PAGTO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'COD_MOD_TRANSACAO', 'CHAR', '', '', '20', 
'4','Código Modalidade Transação','PI_COD_MOD_TRANSACAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'ATRIB_FLEX_1', 'CHAR', '', '', '200', 
'5','Campo flex_field','PI_ATRIB_FLEX_1','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'ATRIB_FLEX_2', 'CHAR', '', '', '200', 
'6','Campo flex_field','PI_ATRIB_FLEX_2','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'ATRIB_FLEX_3', 'CHAR', '', '', '200', 
'7','Campo flex_field','PI_ATRIB_FLEX_3','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'ATRIB_FLEX_4', 'CHAR', '', '', '200', 
'8','Campo flex_field','PI_ATRIB_FLEX_4','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'ATRIB_FLEX_5', 'CHAR', '', '', '200', 
'9','Campo flex_field','PI_ATRIB_FLEX_5','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'INDICADOR', 'CHAR', '', '', '1', 
'10','Indica se tipo de pagamento é por Dia (D) ou por Mês (M)','PI_INDICADOR','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'PERIODICIDADE', 'CHAR', '', '', '2', 
'11','Quantidade de Dias ou de Meses (dependendo do Indicador)','PI_PERIODICIDADE','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_CONDICAO_PAGAMENTO', 'TIPO_TRANSACAO', 'CHAR', '', '', '1', 
'12','','PI_TIPO_TRANSACAO','');

commit;

set serveroutput on
exec PRC_SINCRONIZA_TABELA('BG_CONDICAO_PAGAMENTO');

CREATE OR REPLACE
TRIGGER TI_BG_CONDICAO_PAGAMENTO
BEFORE INSERT ON BG_CONDICAO_PAGAMENTO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	select seq_id_interface.nextval into :new.id from dual;
 
end;
/


CREATE OR REPLACE
TRIGGER TIA_BG_CONDICAO_PAGAMENTO
AFTER INSERT ON BG_CONDICAO_PAGAMENTO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	insert into REGISTROS_INTERFACES (ID, ID_IMPORTACAO, TABLE_NAME, ID_REF)
	values (:new.id, :new.id_importacao, 'BG_CONDICAO_PAGAMENTO', :new.id_ref);
end;
/


CREATE OR REPLACE
TRIGGER TD_BG_CONDICAO_PAGAMENTO
BEFORE DELETE ON BG_CONDICAO_PAGAMENTO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	delete from REGISTROS_INTERFACES where id = :old.id;
end;
/


 
-- //////
-- //////  Não esqueça de reprocessar todos os GRANTS para todos os sistemas
-- //////

