conn &&INOUT_USER/&&INOUT_PASS@&&TNS
--  ///////
--  ///////     Script Gerado a partir do Sistema Gerenciador de Interfaces IN-OUT
--  ///////     TABELA: BG_NCM_SISCOMEX
--  ///////

delete from DEPEND_HEADER_ITEM_TMP;

delete from COLUNAS_TAB_INTERFACE where TABLE_NAME = 'BG_NCM_SISCOMEX';

begin

  update	TAB_INTERFACE             
  set		DESCRICAO = '',
		CTL_NAME = 'BG_NCM_SISCOMEX', 
		PREFIX_FILE = 'NCMSIS', 
		GERAR_CTL = 'S', 
		PRIORIDADE = 0, 
		ODBC_SOURCE_NAME = '', 
		ODBC_USER = '', 
		ODBC_PASSWORD = '', 
		ODBC_TABLE_NAME = '', 
		ODBC_WHERE = '', 
		ODBC_SELECT_ESPECIFICO = '', 
		TIPO_INTERFACE = 'LOADER',
		ORACLE_INITIAL_EXTENT = '', 
		ORACLE_NEXT_EXTENT = '', 
		ORACLE_INDEX_TABLESPACE = '',
		ELIMINAR_REG_EXECUCAO = 'N',
		ID_SISTEMA = 'BG',
		PROCEDURE_NAME = 'PKG_SFW_MIGRACAO_NCM.PRC_NCM_SISCOMEX',
		SEPARADOR = '',
		CTL_FIXO = null,
		TRIGGER1 = null,
		TRIGGER2 = null,
		COMANDO_EXTRA_LOADER = ''
  where TABLE_NAME = 'BG_NCM_SISCOMEX';

  if SQL%notfound then
		insert into TAB_INTERFACE 
		(TABLE_NAME,
		DESCRICAO, 
		CTL_NAME, 
		PREFIX_FILE, 
		GERAR_CTL, 
		PRIORIDADE, 
		ODBC_SOURCE_NAME, 
		ODBC_USER, 
		ODBC_PASSWORD, 
		ODBC_TABLE_NAME, 
		ODBC_WHERE, 
		ODBC_SELECT_ESPECIFICO, 
		TIPO_INTERFACE, 
		ORACLE_INITIAL_EXTENT, 
		ORACLE_NEXT_EXTENT, 
		ORACLE_INDEX_TABLESPACE, 
		ELIMINAR_REG_EXECUCAO, 
		COMANDO_EXTRA_LOADER, 
		ID_SISTEMA, 
		PROCEDURE_NAME, 
		SEPARADOR)
		values
		('BG_NCM_SISCOMEX',
		'',
		'BG_NCM_SISCOMEX', 
		'NCMSIS', 
		'S', 
		0, 
		'', 
		'', 
		'', 
		'', 
		'', 
		'', 
		'LOADER', 
		'', 
		'', 
		'',
		'N',
		'',
		'BG',
		'PKG_SFW_MIGRACAO_NCM.PRC_NCM_SISCOMEX',
		'');
  end if;
end;
/


insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'NCM', 'CHAR', '', '', '8', 
'1','','PI_S_NCM','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DESCRICAO', 'CHAR', '', '', '120', 
'2','','PI_S_DESCRICAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ATUALIZACAO', 'CHAR', '', '', '14', 
'3','','PI_D_ATUALIZACAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'COD_UNIDADE_MEDIDA', 'CHAR', '', '', '4', 
'4','','PI_S_COD_UNIDADE_MEDIDA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ALIQUOTA_II', 'CHAR', '', '', '47', 
'5','','PI_N_ALIQUOTA_II','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_INI_VIG_II', 'CHAR', '', '', '14', 
'6','','PI_D_DATA_INI_VIG_II','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_FIM_VIG_II', 'CHAR', '', '', '14', 
'7','','PI_D_DATA_FIM_VIG_II','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ALIQUOTA_II_MERCOSUL', 'CHAR', '', '', '47', 
'8','','PI_N_ALIQUOTA_II_MERCOSUL','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_INI_VIG_II_MSUL', 'CHAR', '', '', '14', 
'9','','PI_D_DATA_INI_VIG_II_MSUL','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_FIM_VIG_II_MSUL', 'CHAR', '', '', '14', 
'10','','PI_D_DATA_FIM_VIG_II_MSUL','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ALIQUOTA_IPI', 'CHAR', '', '', '47', 
'11','','PI_N_ALIQUOTA_IPI','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_INI_VIG_IPI', 'CHAR', '', '', '14', 
'12','','PI_D_DATA_INI_VIG_IPI','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_FIM_VIG_IPI', 'CHAR', '', '', '14', 
'13','','PI_D_DATA_FIM_VIG_IPI','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ALIQUOTA_PIS', 'CHAR', '', '', '47', 
'14','','PI_N_ALIQUOTA_PIS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_INI_VIG_PIS', 'CHAR', '', '', '14', 
'15','','PI_D_DATA_INI_VIG_PIS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_FIM_VIG_PIS', 'CHAR', '', '', '14', 
'16','','PI_D_DATA_FIM_VIG_PIS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'ALIQUOTA_COFINS', 'CHAR', '', '', '47', 
'17','','PI_N_ALIQUOTA_COFINS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_INI_VIG_COFINS', 'CHAR', '', '', '14', 
'18','','PI_D_DATA_INI_VIG_COFINS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'DATA_FIM_VIG_COFINS', 'CHAR', '', '', '14', 
'19','','PI_D_DATA_FIM_VIG_COFINS','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_NCM_SISCOMEX', 'PIS_COFINS_TIPO_APLIC', 'CHAR', '', '', '1', 
'20','','PI_S_PIS_COFINS_TIPO_APLIC','');

commit;

set serveroutput on
exec PRC_SINCRONIZA_TABELA('BG_NCM_SISCOMEX');

CREATE OR REPLACE
TRIGGER TI_BG_NCM_SISCOMEX
BEFORE INSERT ON BG_NCM_SISCOMEX
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	select seq_id_interface.nextval into :new.id from dual;
 
end;
/


CREATE OR REPLACE
TRIGGER TIA_BG_NCM_SISCOMEX
AFTER INSERT ON BG_NCM_SISCOMEX
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	insert into REGISTROS_INTERFACES (ID, ID_IMPORTACAO, TABLE_NAME, ID_REF)
	values (:new.id, :new.id_importacao, 'BG_NCM_SISCOMEX', :new.id_ref);
end;
/


CREATE OR REPLACE
TRIGGER TD_BG_NCM_SISCOMEX
BEFORE DELETE ON BG_NCM_SISCOMEX
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	delete from REGISTROS_INTERFACES where id = :old.id;
end;
/


 
-- //////
-- //////  Não esqueça de reprocessar todos os GRANTS para todos os sistemas
-- //////

