UNDEFINE USER_MACHINE

--ConstantedoRoleSoftway
UNDEFINE ROLE_SOFTWAY

--ConstantesparaConexão
UNDEFINE TNS

--UsuáriosPadrão
UNDEFINE SOFT_USER
UNDEFINE SOFT_PASS

UNDEFINE IO_USER
UNDEFINE IO_PASS

UNDEFINE INOUT_USER
UNDEFINE INOUT_PASS

UNDEFINE IMPORT_USER
UNDEFINE IMPORT_PASS

UNDEFINE BROKER_USER
UNDEFINE BROKER_PASS

UNDEFINE EXPORT_USER
UNDEFINE EXPORT_PASS

UNDEFINE DRAWBACK_USER
UNDEFINE DRAWBACK_PASS

UNDEFINE CAMBIO_EXP_USER
UNDEFINE CAMBIO_EXP_PASS

UNDEFINE CAMBIO_IMP_USER
UNDEFINE CAMBIO_IMP_PASS

UNDEFINE ESOFT_USER
UNDEFINE ESOFT_PASS

UNDEFINE SOACONSOLE_USER
UNDEFINE SOACONSOLE_PASS

UNDEFINE INTEGRACAO_USER
UNDEFINE INTEGRACAO_PASS

--DemaisUsuários
UNDEFINE RECOF_USER
UNDEFINE REGESP_USER

UNDEFINE SCAN_USER
UNDEFINE SCAN_PASS
UNDEFINE SCAN_TNS
UNDEFINE ROLE_SCAN


--ConstantesdeTable_spaces.
UNDEFINE SFW_DATA_4K
UNDEFINE SFW_DATA_64K
UNDEFINE SFW_DATA_128K
UNDEFINE SFW_DATA_512K
UNDEFINE SFW_DATA_1M
UNDEFINE SFW_INDEX_4K
UNDEFINE SFW_INDEX_64K
UNDEFINE SFW_INDEX_128K
UNDEFINE SFW_INDEX_512K
UNDEFINE SFW_INDEX_1M

UNDEFINE SFW_IO_DATA_4K
UNDEFINE SFW_IO_DATA_64K
UNDEFINE SFW_IO_DATA_128K
UNDEFINE SFW_IO_DATA_512K
UNDEFINE SFW_IO_DATA_1M
UNDEFINE SFW_IO_INDEX_4K
UNDEFINE SFW_IO_INDEX_64K
UNDEFINE SFW_IO_INDEX_128K
UNDEFINE SFW_IO_INDEX_512K
UNDEFINE SFW_IO_INDEX_1M

UNDEFINE SFW_IMPORT_DATA_4K
UNDEFINE SFW_IMPORT_DATA_64K
UNDEFINE SFW_IMPORT_DATA_512K
UNDEFINE SFW_IMPORT_DATA_1M
UNDEFINE SFW_IMPORT_INDEX_4K
UNDEFINE SFW_IMPORT_INDEX_64K
UNDEFINE SFW_IMPORT_INDEX_512K
UNDEFINE SFW_IMPORT_INDEX_1M

UNDEFINE SFW_BROKER_DATA_4K
UNDEFINE SFW_BROKER_DATA_64K
UNDEFINE SFW_BROKER_DATA_512K
UNDEFINE SFW_BROKER_DATA_1M
UNDEFINE SFW_BROKER_INDEX_4K
UNDEFINE SFW_BROKER_INDEX_64K
UNDEFINE SFW_BROKER_INDEX_512K
UNDEFINE SFW_BROKER_INDEX_1M

UNDEFINE SFW_EXPORT_DATA_4K
UNDEFINE SFW_EXPORT_DATA_32K
UNDEFINE SFW_EXPORT_DATA_64K
UNDEFINE SFW_EXPORT_DATA_128K
UNDEFINE SFW_EXPORT_DATA_512K
UNDEFINE SFW_EXPORT_DATA_1M
UNDEFINE SFW_EXPORT_INDEX_4K
UNDEFINE SFW_EXPORT_INDEX_64K
UNDEFINE SFW_EXPORT_INDEX_128K
UNDEFINE SFW_EXPORT_INDEX_512K
UNDEFINE SFW_EXPORT_INDEX_1M

UNDEFINE SFW_DRAWBACK_DATA_4K
UNDEFINE SFW_DRAWBACK_DATA_32K
UNDEFINE SFW_DRAWBACK_DATA_64K
UNDEFINE SFW_DRAWBACK_DATA_128K
UNDEFINE SFW_DRAWBACK_DATA_512K
UNDEFINE SFW_DRAWBACK_DATA_1M
UNDEFINE SFW_DRAWBACK_INDEX_4K
UNDEFINE SFW_DRAWBACK_INDEX_64K
UNDEFINE SFW_DRAWBACK_INDEX_128K
UNDEFINE SFW_DRAWBACK_INDEX_512K
UNDEFINE SFW_DRAWBACK_INDEX_1M

UNDEFINE SFW_CAMBIO_EXP_DATA_4K
UNDEFINE SFW_CAMBIO_EXP_INDEX_4K
UNDEFINE SFW_CAMBIO_EXP_DATA_64K
UNDEFINE SFW_CAMBIO_EXP_INDEX_64K
UNDEFINE SFW_CAMBIO_EXP_DATA_128K
UNDEFINE SFW_CAMBIO_EXP_INDEX_128K
UNDEFINE SFW_CAMBIO_EXP_DATA_512K
UNDEFINE SFW_CAMBIO_EXP_INDEX_512K
UNDEFINE SFW_CAMBIO_EXP_DATA_1M
UNDEFINE SFW_CAMBIO_EXP_INDEX_1M

UNDEFINE SFW_CAMBIO_IMP_DATA_4K
UNDEFINE SFW_CAMBIO_IMP_INDEX_4K
UNDEFINE SFW_CAMBIO_IMP_DATA_64K
UNDEFINE SFW_CAMBIO_IMP_INDEX_64K
UNDEFINE SFW_CAMBIO_IMP_DATA_128K
UNDEFINE SFW_CAMBIO_IMP_INDEX_128K
UNDEFINE SFW_CAMBIO_IMP_DATA_512K
UNDEFINE SFW_CAMBIO_IMP_INDEX_512K
UNDEFINE SFW_CAMBIO_IMP_DATA_1M
UNDEFINE SFW_CAMBIO_IMP_INDEX_1M

UNDEFINE SFW_SOACONSOLE_DATA_4K
UNDEFINE SFW_SOACONSOLE_DATA_32K
UNDEFINE SFW_SOACONSOLE_DATA_64K
UNDEFINE SFW_SOACONSOLE_DATA_128K
UNDEFINE SFW_SOACONSOLE_DATA_512K
UNDEFINE SFW_SOACONSOLE_DATA_1M
UNDEFINE SFW_SOACONSOLE_INDEX_4K
UNDEFINE SFW_SOACONSOLE_INDEX_64K
UNDEFINE SFW_SOACONSOLE_INDEX_128K
UNDEFINE SFW_SOACONSOLE_INDEX_512K
UNDEFINE SFW_SOACONSOLE_INDEX_1M

UNDEFINE SFW_REGINT_DATA_4K
UNDEFINE SFW_REGINT_DATA_64K
UNDEFINE SFW_REGINT_DATA_128K
UNDEFINE SFW_REGINT_DATA_512K
UNDEFINE SFW_REGINT_DATA_1M
UNDEFINE SFW_REGINT_INDEX_4K
UNDEFINE SFW_REGINT_INDEX_64K
UNDEFINE SFW_REGINT_INDEX_128K
UNDEFINE SFW_REGINT_INDEX_512K
UNDEFINE SFW_REGINT_INDEX_1M

--ConstanteparaLoginGenérico
UNDEFINE COD_SISTEMA_IMPORT
UNDEFINE COD_SISTEMA_IMPORT_INT
UNDEFINE COD_SISTEMA_BROKER
UNDEFINE COD_SISTEMA_EXPORT
UNDEFINE COD_SISTEMA_EXPORT_INT
UNDEFINE COD_SISTEMA_DRAWBACK
UNDEFINE COD_SISTEMA_CAMBIO_EXP
UNDEFINE COD_SISTEMA_CAMBIO_IMP
UNDEFINE COD_SISTEMA_REGINT