Prompt DEFINE.SQL

-- Tabela CTRL_VERSAO 
DEFINE Versao_Atual     = '01R01P00.1'

define USER_MACHINE     = [PREENCHA/EDITE]

-- Constante do Role Softway
DEFINE ROLE_SOFTWAY = [PREENCHA/EDITE]

-- Constantes para Conexão
DEFINE TNS = [PREENCHA/EDITE]

-- Constant para DBLINK
DEFINE DBLINK_CAI = [PREENCHA/EDITE]
DEFINE DBLINK_APPS = [PREENCHA/EDITE]

-- Usuários Padrão
DEFINE SOFT_USER = [PREENCHA/EDITE]
DEFINE SOFT_PASS = [PREENCHA/EDITE]

DEFINE INOUT_USER = [PREENCHA/EDITE]
DEFINE INOUT_PASS = [PREENCHA/EDITE]

DEFINE INTEGRACAO_USER = [PREENCHA/EDITE]
DEFINE INTEGRACAO_PASS = [PREENCHA/EDITE]

DEFINE IMPORT_USER = [PREENCHA/EDITE]
DEFINE IMPORT_PASS = [PREENCHA/EDITE]

DEFINE BROKER_USER = [PREENCHA/EDITE]
DEFINE BROKER_PASS = [PREENCHA/EDITE]

DEFINE EXPORT_USER = [PREENCHA/EDITE]
DEFINE EXPORT_PASS = [PREENCHA/EDITE]

DEFINE DRAWBACK_USER = [PREENCHA/EDITE]
DEFINE DRAWBACK_PASS = [PREENCHA/EDITE]

DEFINE CAMBIO_EXP_USER = [PREENCHA/EDITE]
DEFINE CAMBIO_EXP_PASS = [PREENCHA/EDITE]

DEFINE CAMBIO_IMP_USER = [PREENCHA/EDITE]
DEFINE CAMBIO_IMP_PASS = [PREENCHA/EDITE]

DEFINE ESOFT_USER = [PREENCHA/EDITE]
DEFINE ESOFT_PASS = [PREENCHA/EDITE]

DEFINE SOACONSOLE_USER = [PREENCHA/EDITE]
DEFINE SOACONSOLE_PASS = [PREENCHA/EDITE]

DEFINE CAI_USER = [PREENCHA/EDITE]
DEFINE CAI_PASS = [PREENCHA/EDITE]

DEFINE APPS_USER = [PREENCHA/EDITE]
DEFINE APPS_PASS =[PREENCHA/EDITE]

-- Demais Usuários
DEFINE RECOF_USER  = [PREENCHA/EDITE]
DEFINE REGESP_USER = [PREENCHA/EDITE]

DEFINE SCAN_USER = [PREENCHA/EDITE]
DEFINE SCAN_PASS = [PREENCHA/EDITE]
DEFINE SCAN_TNS  = [PREENCHA/EDITE]
DEFINE ROLE_SCAN = [PREENCHA/EDITE]

-- Constantes de Table_spaces.
DEFINE SFW_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_IO_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_IO_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_IO_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_IO_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_IO_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_IO_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_IO_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_IO_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_IO_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_IO_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_IMPORT_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_IMPORT_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_BROKER_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_BROKER_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_BROKER_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_BROKER_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_BROKER_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_BROKER_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_BROKER_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_BROKER_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_EXPORT_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_DATA_32K   = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_EXPORT_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_DRAWBACK_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_DATA_32K   = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_DRAWBACK_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_CAMBIO_EXP_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_EXP_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_CAMBIO_IMP_DATA_4K    = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_DATA_64K   = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_DATA_128K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_DATA_1M    = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_INDEX_4K   = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_INDEX_64K  = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_INDEX_128K = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_INDEX_512K = [PREENCHA/EDITE]
DEFINE SFW_CAMBIO_IMP_INDEX_1M   = [PREENCHA/EDITE]

DEFINE SFW_SOACONSOLE_DATA_4K    =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_DATA_32K   =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_DATA_64K   =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_DATA_128K  =  [PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_DATA_512K  = [PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_DATA_1M    =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_INDEX_4K   =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_INDEX_64K  =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_INDEX_128K =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_INDEX_512K =[PREENCHA/EDITE]
DEFINE SFW_SOACONSOLE_INDEX_1M   =[PREENCHA/EDITE]

DEFINE SFW_REGINT_DATA_4K            = [PREENCHA/EDITE]
DEFINE SFW_REGINT_DATA_64K           = [PREENCHA/EDITE]
DEFINE SFW_REGINT_DATA_128K          = [PREENCHA/EDITE]
DEFINE SFW_REGINT_DATA_512K          = [PREENCHA/EDITE]
DEFINE SFW_REGINT_DATA_1M            = [PREENCHA/EDITE]
DEFINE SFW_REGINT_INDEX_4K           = [PREENCHA/EDITE]
DEFINE SFW_REGINT_INDEX_64K          = [PREENCHA/EDITE]
DEFINE SFW_REGINT_INDEX_128K         = [PREENCHA/EDITE]
DEFINE SFW_REGINT_INDEX_512K         = [PREENCHA/EDITE]
DEFINE SFW_REGINT_INDEX_1M           = [PREENCHA/EDITE]

-- Constante para Login Genérico
DEFINE COD_SISTEMA_IMPORT            = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_IMPORT_INT        = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_BROKER            = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_EXPORT            = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_EXPORT_INT        = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_DRAWBACK          = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_CAMBIO_EXP        = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_CAMBIO_IMP        = [PREENCHA/EDITE]
DEFINE COD_SISTEMA_REGINT            = [PREENCHA/EDITE]
