conn &&INOUT_USER/&&INOUT_PASS@&&TNS

--  ///////
--  ///////     Script Gerado a partir do Sistema Gerenciador de Interfaces IN-OUT
--  ///////     TABELA: BG_EMBALAGEM_TIPO
--  ///////

delete from DEPEND_HEADER_ITEM_TMP;

delete from COLUNAS_TAB_INTERFACE where TABLE_NAME = 'BG_EMBALAGEM_TIPO';

begin

  update	TAB_INTERFACE             
  set		DESCRICAO = '',
		CTL_NAME = 'BG_EMBALAGEM_TIPO', 
		PREFIX_FILE = 'EMBTP', 
		GERAR_CTL = 'S', 
		PRIORIDADE = 0, 
		ODBC_SOURCE_NAME = '', 
		ODBC_USER = '', 
		ODBC_PASSWORD = '', 
		ODBC_TABLE_NAME = '', 
		ODBC_WHERE = '', 
		ODBC_SELECT_ESPECIFICO = '', 
		TIPO_INTERFACE = 'LOADER',
		ORACLE_INITIAL_EXTENT = '', 
		ORACLE_NEXT_EXTENT = '', 
		ORACLE_INDEX_TABLESPACE = '',
		ELIMINAR_REG_EXECUCAO = 'N',
		ID_SISTEMA = 'BG',
		PROCEDURE_NAME = 'PKG_SFW_EMBALAGEM.PRC_EMBALAGEM_TIPO',
		SEPARADOR = '',
		CTL_FIXO = null,
		TRIGGER1 = null,
		TRIGGER2 = null,
		COMANDO_EXTRA_LOADER = ''
  where TABLE_NAME = 'BG_EMBALAGEM_TIPO';

  if SQL%notfound then
		insert into TAB_INTERFACE 
		(TABLE_NAME,
		DESCRICAO, 
		CTL_NAME, 
		PREFIX_FILE, 
		GERAR_CTL, 
		PRIORIDADE, 
		ODBC_SOURCE_NAME, 
		ODBC_USER, 
		ODBC_PASSWORD, 
		ODBC_TABLE_NAME, 
		ODBC_WHERE, 
		ODBC_SELECT_ESPECIFICO, 
		TIPO_INTERFACE, 
		ORACLE_INITIAL_EXTENT, 
		ORACLE_NEXT_EXTENT, 
		ORACLE_INDEX_TABLESPACE, 
		ELIMINAR_REG_EXECUCAO, 
		COMANDO_EXTRA_LOADER, 
		ID_SISTEMA, 
		PROCEDURE_NAME, 
		SEPARADOR)
		values
		('BG_EMBALAGEM_TIPO',
		'',
		'BG_EMBALAGEM_TIPO', 
		'EMBTP', 
		'S', 
		0, 
		'', 
		'', 
		'', 
		'', 
		'', 
		'', 
		'LOADER', 
		'', 
		'', 
		'',
		'N',
		'',
		'BG',
		'PKG_SFW_EMBALAGEM.PRC_EMBALAGEM_TIPO',
		'');
  end if;
end;
/


insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'TP_EMB', 'CHAR', '', '', '20', 
'1','Tipo de Embalagem','P_TP_EMB','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'NCM', 'CHAR', '', '', '8', 
'2','NCM','P_NCM','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'DESC_TP_EMB', 'CHAR', '', '', '200', 
'3','Descrição do Tipo de Embalagem','P_DESC_TP_EMB','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'TP_EMBALAGEM_SISCOMEX', 'CHAR', '', '', '2', 
'4','Código do Tipo de Embalagem do Siscomex','P_TP_EMBALAGEM_SISCOMEX','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'COD_UNIDADE_MEDIDA_DIMENSAO', 'CHAR', '', '', '4', 
'5','Código da Unidade de Medida da Dimensão da Embalagem','P_COD_UNIDADE_MEDIDA_DIMENSAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'COD_UNIDADE_MEDIDA_PESO', 'CHAR', '', '', '4', 
'6','Código da Unidade de Medida do Peso da Embalagem','P_COD_UNIDADE_MEDIDA_PESO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'ALTURA', 'CHAR', '', '', '47', 
'7','Altura da Embalagem','P_ALTURA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'LARGURA', 'CHAR', '', '', '47', 
'8','Largura da embalagem','P_LARGURA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'COMPRIMENTO', 'CHAR', '', '', '47', 
'9','Comprimento da Embalagem','P_COMPRIMENTO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'PESO_EMBALAGEM', 'CHAR', '', '', '47', 
'10','Peso da embalagem','P_PESO_EMBALAGEM','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'IC_ALTURA_VARIAVEL', 'CHAR', '', '', '1', 
'11','Controla se Altura Variável (S/N)','P_IC_ALTURA_VARIAVEL','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'IC_CONTAINER', 'CHAR', '', '', '1', 
'12','Controla se Embalagem é Container (S/N)','P_IC_CONTAINER','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'IC_PRIMARIA', 'CHAR', '', '', '1', 
'13','Controla se Embalagem é Primária (S/N)','P_IC_PRIMARIA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'IC_PADRAO', 'CHAR', '', '', '1', 
'14','Controla se Embalagem é Padrão (S/N)','P_IC_PADRAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'IC_RETORNAVEL', 'CHAR', '', '', '1', 
'15','Controla se Embalagem é Retornável (S/N)','P_IC_RETORNAVEL','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'ABREVIACAO_TP_EMB', 'CHAR', '', '', '2', 
'16','Abreviação do Tipo de embalagem','P_ABREVIACAO_TP_EMB','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'PRECO', 'CHAR', '', '', '47', 
'17','Preço da Embalagem','P_PRECO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'POSICAO_RELATORIO', 'CHAR', '', '', '1', 
'18','Posição da Embalagem no Relatório','P_POSICAO_RELATORIO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'COD_MOEDA', 'CHAR', '', '', '25', 
'19','Código da Moeda','P_COD_MOEDA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'VOLUME', 'CHAR', '', '', '47', 
'20','Volume total da Embalagem','P_VOLUME','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'PESO_MAXIMO_EMB', 'CHAR', '', '', '47', 
'21','Peso máximo da Embalagem','P_PESO_MAXIMO_EMB','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'VOLUME_MAXIMO_EMB', 'CHAR', '', '', '47', 
'22','Volume máximo da Embalagem','P_VOLUME_MAXIMO_EMB','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'ID_EMB_TP_DESIGNACAO', 'CHAR', '', '', '20', 
'23','Código do tipo do Embalamento: 1 – Embalagem Primária 2 – Embalagem 3 – Pallet 4 - Container','P_ID_EMB_TP_DESIGNACAO','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'TARA', 'CHAR', '', '', '47', 
'24','Tara da embalagem','P_TARA','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'PART_NUMBER', 'CHAR', '', '', '100', 
'25','','P_PART_NUMBER','');

insert into COLUNAS_TAB_INTERFACE
(TABLE_NAME, COLUMN_NAME, TIPO_LOADER, FORMATO, COMANDO_EXTRA, TAMANHO, ORDEM, DESCRICAO, ARG_NAME, ARG_FUNCTION)
values
('BG_EMBALAGEM_TIPO', 'COD_ORGANIZACAO', 'CHAR', '', '', '100', 
'26','','P_COD_ORGANIZACAO','');

commit;

set serveroutput on
exec PRC_SINCRONIZA_TABELA('BG_EMBALAGEM_TIPO');

CREATE OR REPLACE
TRIGGER TI_BG_EMBALAGEM_TIPO
BEFORE INSERT ON BG_EMBALAGEM_TIPO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	select seq_id_interface.nextval into :new.id from dual;
 
end;
/


CREATE OR REPLACE
TRIGGER TIA_BG_EMBALAGEM_TIPO
AFTER INSERT ON BG_EMBALAGEM_TIPO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	insert into REGISTROS_INTERFACES (ID, ID_IMPORTACAO, TABLE_NAME, ID_REF)
	values (:new.id, :new.id_importacao, 'BG_EMBALAGEM_TIPO', :new.id_ref);
end;
/


CREATE OR REPLACE
TRIGGER TD_BG_EMBALAGEM_TIPO
BEFORE DELETE ON BG_EMBALAGEM_TIPO
REFERENCING OLD AS old NEW AS new
FOR EACH ROW
begin
	delete from REGISTROS_INTERFACES where id = :old.id;
end;
/


 
-- //////
-- //////  Não esqueça de reprocessar todos os GRANTS para todos os sistemas
-- //////

